language: php
sudo: required
dist: xenial

env:
  - DB_CONNECTION=mysql

services:
  - mysql

php:
  - 7.2

addons:
  chrome: stable

install:
  - mysql -e 'create database homestead;'
  - cp .env.travis .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  - php artisan migrate

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml tests/
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
