version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: laravel-mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - MYSQL_DATABASE=${DB_DATABASE}
      ports:
        - "${MYSQL_PORT}:3306"

    mysql-test:
      image: mysql:5.7
      container_name: laravel-mysql-test
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_TEST_PASSWORD}
        - MYSQL_DATABASE=${DB_TEST_DATABASE}
      ports:
        - "${MYSQL_TEST_PORT}:3306"

    webserver:
      image: nginx:alpine
      container_name: laravel-webserver
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "${APP_PORT}:80"
      depends_on:
        - mysql
        - mysql-test
        - php-fpm

    php-fpm:
      build: docker/php-fpm
      container_name: laravel-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      entrypoint: bash -c "./entrypoint.sh && /usr/sbin/php-fpm7.4 -O"

    node:
      build: docker/node
      container_name: laravel-node

    mailhog:
      image: mailhog/mailhog
      container_name: laravel-mailhog
      ports:
        - "${MAILHOG_PORT}:8025"

    minio:
      image: minio/minio
      container_name: laravel-minio
      command: server /data
      volumes:
        - ./docker/minio/data:/data
      ports:
        - "${MINIO_PORT}:9000"
      environment:
        MINIO_ACCESS_KEY: ${AWS_KEY}
        MINIO_SECRET_KEY: ${AWS_SECRET}
