<?php

namespace App\Enums;

use BenSampo\Enum\Enum;

final class AdminStatus extends Enum
{
    const ACTIVE = 1;
    const INACTIVE = 0;

    public static function getDescription($value): string
    {
        if ($value == self::ACTIVE) {
            return __('Active');
        }

        if ($value == self::INACTIVE) {
            return __('Inactive');
        }

        return parent::getDescription($value); // TODO: Change the autogenerated stub
    }
}
